[profile.default]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 500
fs_permissions = [{ access = "read", path = "./" }]

[profile.ci]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 500
deny_warnings = true
