name: ✨ Feature Request
description: Suggest a new feature or enhancement for FTH-G
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check these items before submitting
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: I have checked the roadmap and this isn't already planned
          required: true
        - label: This is a feature request, not a bug report
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Smart Contract Enhancement
        - Oracle/Price Feed Improvement
        - User Interface/Experience
        - API/Integration
        - Security Enhancement
        - Performance Optimization
        - Documentation
        - Developer Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current use case)
        - High (Significantly improves workflow)
        - Medium (Nice to have improvement)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current limitation or pain point that this feature would address.
        What workflow or use case is currently difficult or impossible?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your ideal solution in detail. Include:
        - What the feature should do
        - How users would interact with it
        - Any specific requirements or constraints
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered.
        Why is your proposed solution preferred?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        Provide concrete examples of how this feature would be used:
        - User personas who would benefit
        - Specific workflows that would improve
        - Integration scenarios
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Considerations
      description: Any technical details or requirements?
      placeholder: |
        If you have technical background, please share:
        - Suggested implementation approach
        - Technical constraints or requirements
        - Integration points with existing system
        - Performance considerations

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Visual representations or examples
      placeholder: |
        If applicable, provide:
        - UI mockups or wireframes
        - Code examples showing desired API
        - Screenshots from other platforms with similar features
        - Flow diagrams

  - type: checkboxes
    id: impact
    attributes:
      label: Expected Impact
      description: What would be the impact of this feature?
      options:
        - label: Improves developer experience
        - label: Enhances user experience
        - label: Increases security
        - label: Improves performance
        - label: Enables new use cases
        - label: Reduces operational overhead
        - label: Improves compliance/regulatory alignment

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Implementation Effort
      description: What's your guess on implementation complexity?
      options:
        - Small (Few hours to 1 day)
        - Medium (2-5 days)
        - Large (1-2 weeks)
        - Very Large (Multiple weeks)
        - Unknown

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What's the business case for this feature?
      placeholder: |
        Explain the value this feature would provide:
        - User acquisition/retention benefits
        - Revenue impact
        - Competitive advantages
        - Risk mitigation

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with design/specification
        - label: I can help with implementation
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide funding/bounty for development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information relevant to this feature request
      placeholder: |
        - Links to relevant documentation or examples
        - Timeline constraints
        - Related features or dependencies
        - Community feedback or discussions